CREATE TABLE IF NOT EXISTS fnd_app_install_trend_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_slot DATETIME NOT NULL,
  target_date DATE NOT NULL,
  window_started_at DATETIME NOT NULL,
  window_ended_at DATETIME NOT NULL,
  status ENUM('success', 'failed') NOT NULL DEFAULT 'failed',
  apps_checked INT UNSIGNED NOT NULL DEFAULT 0,
  metrics_saved INT UNSIGNED NOT NULL DEFAULT 0,
  alerts_created INT UNSIGNED NOT NULL DEFAULT 0,
  messages_queued INT UNSIGNED NOT NULL DEFAULT 0,
  summary_json LONGTEXT DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  started_at DATETIME NOT NULL,
  finished_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_app_install_trend_runs_slot (run_slot),
  KEY idx_app_install_trend_runs_status_finished (status, finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fnd_app_install_trend_app_metrics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  app_id INT UNSIGNED NOT NULL,
  app_name VARCHAR(120) NOT NULL,
  platform VARCHAR(32) NOT NULL,
  app_db VARCHAR(100) NOT NULL,
  registration_table VARCHAR(80) NOT NULL,
  metric_date DATE NOT NULL,
  analysis_slot DATETIME NOT NULL,
  window_started_at DATETIME NOT NULL,
  window_ended_at DATETIME NOT NULL,
  current_installs INT UNSIGNED NOT NULL DEFAULT 0,
  previous_day_installs INT UNSIGNED NOT NULL DEFAULT 0,
  two_days_ago_installs INT UNSIGNED NOT NULL DEFAULT 0,
  previous_day_drop_percent DECIMAL(8,2) DEFAULT NULL,
  two_day_drop_percent DECIMAL(8,2) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_app_install_trend_metric_run_app (run_id, app_id),
  KEY idx_app_install_trend_metric_app_date (app_id, metric_date),
  KEY idx_app_install_trend_metric_slot (analysis_slot)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fnd_app_install_trend_alerts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED DEFAULT NULL,
  app_id INT UNSIGNED NOT NULL,
  app_name VARCHAR(120) NOT NULL,
  platform VARCHAR(32) NOT NULL,
  app_db VARCHAR(100) NOT NULL,
  registration_table VARCHAR(80) NOT NULL,
  metric_date DATE NOT NULL,
  analysis_slot DATETIME NOT NULL,
  window_started_at DATETIME NOT NULL,
  window_ended_at DATETIME NOT NULL,
  current_installs INT UNSIGNED NOT NULL DEFAULT 0,
  previous_day_installs INT UNSIGNED NOT NULL DEFAULT 0,
  two_days_ago_installs INT UNSIGNED NOT NULL DEFAULT 0,
  baseline_date DATE NOT NULL,
  baseline_installs INT UNSIGNED NOT NULL DEFAULT 0,
  drop_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  threshold_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  alert_type ENUM('drop_vs_previous_day', 'drop_vs_two_days_ago') NOT NULL,
  severity ENUM('watch', 'critical') NOT NULL DEFAULT 'watch',
  message TEXT NOT NULL,
  status ENUM('open', 'queued', 'sent', 'dismissed') NOT NULL DEFAULT 'open',
  whatsapp_queue_id BIGINT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_app_install_trend_alert (app_id, platform, metric_date, analysis_slot, alert_type),
  KEY idx_app_install_trend_alert_status (status, created_at),
  KEY idx_app_install_trend_alert_date (metric_date, platform),
  KEY idx_app_install_trend_alert_queue (whatsapp_queue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fnd_whatsapp_message_queue (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_type VARCHAR(80) NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  group_name VARCHAR(120) NOT NULL DEFAULT 'INFO',
  message MEDIUMTEXT NOT NULL,
  status ENUM('pending', 'processing', 'sent', 'failed') NOT NULL DEFAULT 'pending',
  attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
  next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_at DATETIME DEFAULT NULL,
  sent_at DATETIME DEFAULT NULL,
  last_error TEXT DEFAULT NULL,
  response_text LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_whatsapp_message_queue_source (source_type, source_id),
  KEY idx_whatsapp_message_queue_status_next (status, next_attempt_at),
  KEY idx_whatsapp_message_queue_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
