
import { z } from 'zod';

export const globalSettingsSchema = z.object({
  service_account_json: z.string().optional(),
  google_services_json: z.string().optional(),
  dashboard_cards_json: z.string().optional(),
  navigation_visibility_json: z.string().optional(),
  exchange_rates_json: z.string().optional(),
  company_logo_url: z.string().url().optional(),
  initial_screen: z.string().optional(),
  demo_mode_info_cards: z.boolean().optional(),
  demo_mode_app_charts: z.boolean().optional(),
  demo_mode_financial_summary: z.boolean().optional(),
  debug_info_visibility: z.boolean().optional(),
  php_auth_token: z.string().optional(),
  in_app_ad_upload_path: z.string().optional(),
  in_app_ad_upload_url: z.string().optional(),
  finance_upload_path: z.string().optional(),
  finance_upload_url: z.string().optional(),
  app_store_connect_api_key_id: z.string().optional(),
  app_store_connect_api_issuer_id: z.string().optional(),
  app_store_connect_api_private_key: z.string().optional(),
  app_store_connect_vendor_number: z.string().optional(),
  admob_client_id: z.string().optional(),
  admob_client_secret: z.string().optional(),
  admob_refresh_token: z.string().optional(),
  admob_publisher_id: z.string().optional(),
  google_ads_client_id: z.string().optional(),
  google_ads_client_secret: z.string().optional(),
  google_ads_refresh_token: z.string().optional(),
  google_ads_developer_token: z.string().optional(),
  google_ads_customer_id: z.string().optional(),
  google_ads_login_customer_id: z.string().optional(),
  google_ads_api_version: z.string().optional(),
  tax_gmail_client_id: z.string().optional(),
  tax_gmail_client_secret: z.string().optional(),
  tax_gmail_refresh_token: z.string().optional(),
  tax_gmail_mailbox: z.string().optional(),
  tax_gmail_income_label: z.string().optional(),
  tax_gmail_expense_label: z.string().optional(),
  tax_gmail_approved_label: z.string().optional(),
  tax_imap_host: z.string().optional(),
  tax_imap_port: z.string().optional(),
  tax_imap_encryption: z.string().optional(),
  tax_imap_mailbox: z.string().optional(),
  tax_imap_username: z.string().optional(),
  tax_imap_password: z.string().optional(),
  tax_veryfi_enabled: z.boolean().optional(),
  tax_veryfi_client_id: z.string().optional(),
  tax_veryfi_username: z.string().optional(),
  tax_veryfi_api_key: z.string().optional(),
  tax_veryfi_client_secret: z.string().optional(),
  tax_veryfi_environment_url: z.string().optional(),
  tax_ocr_space_enabled: z.boolean().optional(),
  tax_ocr_space_api_key: z.string().optional(),
  tax_ocr_space_endpoint: z.string().optional(),
  tax_ocr_space_language: z.string().optional(),
  tax_ocr_space_engine: z.string().optional(),
  tax_evidence_save_enabled: z.boolean().optional(),
  tax_evidence_storage_provider: z.string().optional(),
  tax_uploadcare_public_key: z.string().optional(),
  tax_uploadcare_secret_key: z.string().optional(),
  tax_uploadcare_store: z.string().optional(),
  tax_drive_save_enabled: z.boolean().optional(),
  tax_drive_folder_id: z.string().optional(),
});

export type GlobalSettings = z.infer<typeof globalSettingsSchema>;
