create table if not exists public.test_table (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists test_table_is_active_idx
  on public.test_table (is_active);

insert into public.test_table (title, description)
values ('Test Row', 'Sample row for Supabase connection verification')
on conflict do nothing;

