create table if not exists public.fnd_app_details_tab (
  id integer generated by default as identity primary key,
  package_name varchar(100) not null,
  db_name varchar(50) not null,
  name varchar(50) not null,
  theme_color varchar(50) not null,
  current_ver varchar(10) not null,
  release_date date not null,
  paid integer not null default 0,
  os varchar(10) not null,
  url varchar(300) not null,
  private_key text,
  endpoint varchar(300),
  client_id varchar(100),
  client_email varchar(300) not null,
  app_order integer not null default 0,
  icon_url varchar(250),
  landscapeSupport integer not null default 0,
  status integer not null default 4,
  log_level integer not null default 0,
  server_folder varchar(30),
  auth_account varchar(200),
  nav_param varchar(60)
);

create unique index if not exists fnd_app_details_tab_package_name_key
  on public.fnd_app_details_tab (package_name);

create unique index if not exists fnd_app_details_tab_db_name_key
  on public.fnd_app_details_tab (db_name);

create index if not exists fnd_app_details_tab_app_order_idx
  on public.fnd_app_details_tab (app_order);

create index if not exists fnd_app_details_tab_status_idx
  on public.fnd_app_details_tab (status);

comment on table public.fnd_app_details_tab is 'Master app registry for RER MedApps admin system.';

